### PR TITLE
Automate the upload to PyPI via CI

### PR DESCRIPTION
**Pull request by igorauad**
Add job on the build workflow to automate the uploading to PyPi. Upload the
source distribution file (produced by sdist) and all built wheels (.whl files).

The implementation is based on the [example from cibuildwheel](https://github.com/joerick/cibuildwheel/blob/master/examples/github-deploy.yml), except for the tag
format. Expect version tags to be formatted as `zfec-x.y.z`.

This job requires [secret](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) `pypi_password` to be set on the repository.

### CODE REVIEW

**Review by sajith — COMMENTED** [review]
Thanks, @igorauad!  

The PR look good to me, but I do not have the privilege to manage secrets in this repository.  Unless we set the secret correctly, I expect that `upload_pypi` will fail even if I go ahead and merge this PR.  I don't know who can/should manage sedcrets either.  Which is why I took the lazy route and omitted adding this bit when I initially added cibuildwheel configuration. ;-)

Also, zfec is not a super active project, so I was unsure the hassle of automating this step would be worthwhile.

I don't know the deal with failing windows-latest/pypy3 CI failures.  I probably should investigate that.

**Comment by igorauad** [comment]
@sajith Thanks for your reply. I see. It's probably a similar effort to push to PyPI manually this time and to review the PR. But anyway, it's a convenience that could help in the future. It wouldn't hurt for sure :)

Nevertheless, as I pointed out in #32 , I'm more interested in solving the missing 1.5.4 on PyPI. The PR was just a related change.

> Unless we set the secret correctly, I expect that upload_pypi will fail even if I go ahead and merge this PR.

For sure. Anyway, I suppose the person/maintainer who has admin rights on this repo might be the person who has the token to push to PyPI. So my problem (the missing 1.5.4 on PyPI) is in his/her hands anyways :)

> I don't know the deal with failing windows-latest/pypy3 CI failures. I probably should investigate that.

I saw that but didn't look further, as I didn't touch any python code. Shall I re-run and see if there is any racing or something? Or did you just re-run it?

**Comment by sajith** [comment]
> I saw that but didn't look further, as I didn't touch any python code. Shall I re-run and see if there is any racing or something? Or did you just re-run it?

I did re-run it, and it resulted in the same error.  I guess Windows/pypy3 setup on GitHub Actions has changed since it was last tested.  I will investigate, but I am sure that failure is not relevant to this PR anyway.

**Comment by exarkun** [comment]
It looks like I have upload permission to zfec.  I can try to get this landed.

**Comment by exarkun** [comment]
#62 has some more changes I thought would be interesting to go along with this, and is in-repo so it can get the secrets from GitHub Actions and demonstrate the automation works on test.pypi.org.

**Pull request closed without merging**
