### PR TITLE
Python 3.12 support

### LINKED ISSUE #99: Python 3.12 support
At minimum, the version of `versioneer` used doesn't support 3.12. But there may be other issues. I will submit PR soon.

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #99 

Not sure what's up with both NEWS and ChangeLog existing, so didn't do an entry. Someone with permissions will have to do a release once this is merged.

### CODE REVIEW

**Comment by itamarst** [comment]
Most of the changes are just upgrading versioneer.

**Comment by sajith** [comment]
@itamarst I too do not know what the deal is with both NEWS.txt and changelog, although I myself have added some notes to both of them (sorry!).  What do you think would be the right thing to do?

It also bugs me that we get a bunch of deployment errors from PR checks, because zfec version that CI attempts to upload already exists on testpypi.  Maybe we should skip testpypi upload? 

Relatedly, is it a good idea to continue vendoring versioneer anymore?  Perhaps setuptools_scm (or similar) will do an acceptable job, and if we switch to setuptools_scm testpypi publishing will stop failing?

**Comment by sajith** [comment]
Wait, testpypi uploads are failing with [a different error](https://github.com/tahoe-lafs/zfec/actions/runs/6564072558/job/17829960318?pr=100#step:4:109) now:

```
ERROR    HTTPError: 403 Forbidden from https://test.pypi.org/legacy/            
         Invalid or non-existent authentication information. See                
         https://test.pypi.org/help/#invalid-auth for more information.    
```

Pretty sure that the earlier pypi upload failures were because of attempts to re-upload existing versions of zfec package.

**Comment by itamarst** [comment]
I am not sure `setuptools_scm` would make any difference; if the issue is it has the same version, that would still be the case I think? In theory there's some `post`-version stuff, not sure why that's not triggered.

**Comment by sajith** [comment]
What I've seen is that setuptools_scm will insert a git short commit hash in the package name (resulting in package names of the form  `zfec-x.y.z+deadb33f-cp32-abi3-linux_x86_64.whl`), so testpypi uploads will have unique names.

**Comment by itamarst** [comment]
I thought versioneer did that too, e.g. on my (untagged) fork, it gives `zfec-0.post0.dev675-cp312-cp312-linux_x86_64.whl`.

**Comment by sajith** [comment]
Ah okay, versioneer should be able to do the job just fine then.

I will look into these testpypi failures when I get a chance.

**Review by sajith — APPROVED** [review]

**Comment by exarkun** [comment]
> Wait, testpypi uploads are failing with [a different error](https://github.com/tahoe-lafs/zfec/actions/runs/6564072558/job/17829960318?pr=100#step:4:109) now:
> 
> ```
> ERROR    HTTPError: 403 Forbidden from https://test.pypi.org/legacy/            
>          Invalid or non-existent authentication information. See                
>          https://test.pypi.org/help/#invalid-auth for more information.    
> ```
> 
> Pretty sure that the earlier pypi upload failures were because of attempts to re-upload existing versions of zfec package.

I think this error is due to the PR being submitted from a fork and so not having access to any secrets.

**Pull request merged**
