### PR TITLE
Use pbr for packaging python module and clean up setup.py

### PR DESCRIPTION
**Pull request by copyninja**
Use pbr (Python build reasonableness) for managing the setuptools packaging. I've mimicked most functionality in existing setup.py except the extra_requires. extra_requires points to a hash which I'm not clear is really used or just a left over.

I would be happy to get a review on my changes.

### CODE REVIEW

**Comment by copyninja** [comment]
I will reopen the PR once I fix travis error.

**Comment by copyninja** [comment]
@vu3rdd I would be happy if you can have a look at the changes and provide some feedback.

**Comment by warner** [comment]
Hey, this is a great direction to go. Could you try to address a few problems?:

* pull in the changes I made (on top of your branch) in https://github.com/warner/zfec/tree/pr5 , which fixes a bunch of typos (the metadata changed in your branch, which probably wasn't your intention), fixes the --stride= argument, and removes the old setup.py/setup.cfg files (which are still in git history if we ever need them).
* this switch to PBR causes the computed version string to break (try a `setup.py --version`: it should be 1.4.24-something, but it comes out as 0.0.1-something). We were using Versioneer before, which looked for a git tag with a `zfec-` prefix, and I'm guessing PBR can't handle tags with prefixes. Is there any way we can keep using Versioneer?
* I'd love for the standard test command to be just "run `tox`". I *think* this will still accomplish that, but could you change the `.travis.yml` to use tox too? In particular I'd like to see that `pip install -r requirements.txt` removed from .travis.yml, if that's not what we'd advise devs to use. Tox should install the deps itself (or, rather, tox should `pip install -e .`, and pip should get the deps, via `install_requires=`)
* running `setup.py` appears to modify `./changelog`, which isn't a great thing for a build step to do. I think it also created an `AUTHORS` file which wasn't there before.
* the `.eggs/` directory needs to be added to `.gitignore`, if it's going to be populated through the `setup_requires=`

thanks!

**Comment by copyninja** [comment]
@warner Thanks for the review and support in IRC :-). I've done all the changes you asked for. Please let me know if you think some more changes needed for the same.

**Comment by warner** [comment]
No worries :)

In tox.ini, I notices that you're using ``deps = --editable=.`, which seems like a bit of a hack. Doesn't Tox have some easier way to express that, like `develop = true` or something?

**Comment by copyninja** [comment]
Not very familiar with tox. I'll have a look at docs and update it. But I
guess I copied it from Tahoe tox.ini

**Comment by copyninja** [comment]
@warner I removed `deps` and added `usedevelop` and it does the same as previous `deps=--editable=.`. Let me know if anything else needs to be tuned.

**Comment by warner** [comment]
I've rebased this to current master (the recent py3 support caused quite a few conflicts), and squashed it to a single commit (to make the merge easier). I'll land this new branch momentarily. Thanks!

**Pull request closed without merging**
